### PR TITLE
:bug: Fix CSV-table caption

### LINKED ISSUE #1273: CSV-tables are missing the "Table." enumerator
See the documentation

image

### PR DESCRIPTION
**Pull request by agoose77**
This PR ensures that we wrap captions in CSV-table nodes with the `caption` node.

Fixes #1273

### CODE REVIEW

File: packages/myst-directives/src/table.ts [hunk 1]
```diff
@@ -326,13 +334,14 @@ export const csvTableDirective: DirectiveSpec = {
...
     };
+
     const container = {
       type: 'container',
       kind: 'table',
       identifier: identifier,
       label: label,
       class: data.options?.class,
-      children: [...((data.arg ?? []) as GenericNode[]), table],
+      children: [...captions, table],
```
Comment (stevejpurves) [inline packages/myst-directives/src/table.ts:344]: @agoose77 looks good, I guess just plain text was getting inserted before without proper styling/numbering hookup?
