### PR TITLE
🧮 Fix AMSMath environment for LaTeX

### LINKED ISSUE #974: MD -> LaTeX: `gather` is not properly generated
## Description

Consider the following document:
```markdown
Some introduction text

\begin{gather}
    E=mc^2
\end{gather}
```

The issue is that the LaTeX document that it generates becomes:
```latex
Some introduction text

\begin{equation}
\begin{gather}
    E=mc^2
\end{gather}
\end{equation}
```

This should not be surrounded by `equation` block

## Proposed solution

- Distinguish which environments need to be within a math environment, e.g. `gathered` vs `gather`
- Distinguish which environments handle numbering `gathered` vs `gather`
- Distinguish when we want something to be numbered and not `gather` vs `gather*`

Then conditionally add either `equation` or `equation*` or nothing to the LaTeX document

### PR DESCRIPTION
**Pull request by LecrisUT**
Closes #974

### CODE REVIEW

**Comment by LecrisUT** [comment]
Print-style debugging is slow, and I can't seem to get `--enable-source-maps` to help me. So far I know that at the point where it tries to run
```typescript
const plugin: Plugin<[Options?], Root, VFile> = function (opts) {
  this.Compiler = (node, file) => {
    transformLegends(node);

    const state = new TexSerializer(file, node, opts ?? { handlers });
```
The `type=math` is already set for the block in `node`

**Comment by LecrisUT** [comment]
Ok, this for now handles the issue according to https://github.com/executablebooks/mystmd/issues/974#issuecomment-1994651762 approach.

**Comment by rowanc1** [comment]
@LecrisUT thanks for the PR - I added a few test cases (feel free to add some more) and extended to other ams environments that should not be wrapped in equation environments.

I think this is an incremental improvement, however, we are not yet handling labels correctly (I don't think).

I removed the throw from your code, we can add an error to the tree/console there if we want to highlight it, but I think following up with another PR might be best.

Let me know if you are happy with the changes and we can get it in and released.

File: packages/myst-to-tex/src/math.ts [hunk 1]
```diff
@@ -1,5 +1,35 @@
...
+  'Vmatrix',
+  'eqnarray',
+];
+
+const RE_OPEN = new RegExp(`^\\\\begin{(${ENVIRONMENTS.join('|')})([*]?)}`);
+
+function isAmsmathEnvironment(value: string) {
+  const matchOpen = value.trim().match(RE_OPEN);
+  if (!matchOpen) return false;
+  const [, environment, numbered] = matchOpen;
```
Comment (LecrisUT) [inline packages/myst-to-tex/src/math.ts:26]:
```suggestion
  const [, environment, not_numbered] = matchOpen;
```

Probably should convert it to proper bool at the end as well. Doesn't really make a difference here, but it might confuse when coming back.

File: packages/myst-to-tex/src/math.ts [hunk 2]
```diff
@@ -1,5 +1,35 @@
...
+  const end = `\\end{${environment}${numbered}}`;
+  const matchClose = value.trim().endsWith(end);
+  if (!matchClose) return false;
```
Comment (LecrisUT) [inline packages/myst-to-tex/src/math.ts:29]: Should it throw an execption here? The LaTeX part would also fail to compile anyway, and at least it can display nicer error message than the LaTeX logs

File: packages/myst-to-tex/src/math.ts (hunk 1 above)
Comment (rowanc1) [reply packages/myst-to-tex/src/math.ts:26]: Updated to `start` and returning a boolean. Thanks!

File: packages/myst-to-tex/src/math.ts (hunk 2 above)
Comment (rowanc1) [reply packages/myst-to-tex/src/math.ts:29]: There will already be an error shown when katex tries to compile this, so I think it is ok to leave this out here.

**Comment by rowanc1** [comment]
Thanks again @LecrisUT for all your help in recent days! Excited to get this released soon.
